- hosts: terraform-ansible
  tasks: 
  - name: Criando o arquivo index
    copy: 
      dest: /home/ubuntu/index.html
      content: <h1>Feito com terraform e ansible Terceiro teste</h1>
  - name: Criando o servidor
    shell: "nohup busybox httpd -f -p 8080 &" 